### ISSUE TITLE
Build with yarn 4.6.0 doesn't work

### ISSUE THREAD

**Issue by mfmanca2000** [tevonsb/homeassistant-mcp#4]
I'm using yarn 4.6.0
Launched yarn install and then yarn build on the main branch (the only one)
These are all the errors I'm getting

```
PS C:\dev\homeassistant-mcp> yarn build
src/index.ts:165:7 - error TS2322: Type 'TRawEntityIds' is not assignable to type 'PICK_ENTITY<"switch"> | PICK_ENTITY<"switch">[]'.
  Type '"person.digital_alchemy"' is not assignable to type 'PICK_ENTITY<"switch"> | PICK_ENTITY<"switch">[]'.

165       entity_id: params.entity_id,
          ~~~~~~~~~

  node_modules/@digital-alchemy/hass/dist/dynamic.d.mts:3051:13
    3051             entity_id: PICK_ENTITY<"switch"> | PICK_ENTITY<"switch">[];
                     ~~~~~~~~~
    The expected type comes from property 'entity_id' which is declared here on type '{ entity_id: PICK_ENTITY<"switch"> | PICK_ENTITY<"switch">[]; }'

src/index.ts:169:5 - error TS2322: Type 'TRawEntityIds' is not assignable to type 'PICK_ENTITY<"switch"> | PICK_ENTITY<"switch">[]'.
  Type '"person.digital_alchemy"' is not assignable to type 'PICK_ENTITY<"switch"> | PICK_ENTITY<"switch">[]'.

169     entity_id: params.entity_id,
        ~~~~~~~~~

  node_modules/@digital-alchemy/hass/dist/dynamic.d.mts:3035:13
    3035             entity_id: PICK_ENTITY<"switch"> | PICK_ENTITY<"switch">[];
                     ~~~~~~~~~
    The expected type comes from property 'entity_id' which is declared here on type '{ entity_id: PICK_ENTITY<"switch"> | PICK_ENTITY<"switch">[]; }'

src/index.ts:175:27 - error TS2339: Property 'alarm_control_panel' does not exist on type 'iCallService'.

175     return hass.hass.call.alarm_control_panel.alarm_arm_away({
                              ~~~~~~~~~~~~~~~~~~~

src/index.ts:180:27 - error TS2339: Property 'alarm_control_panel' does not exist on type 'iCallService'.

180     return hass.hass.call.alarm_control_panel.alarm_disarm({
                              ~~~~~~~~~~~~~~~~~~~

src/index.ts:185:27 - error TS2339: Property 'alarm_control_panel' does not exist on type 'iCallService'.

185     return hass.hass.call.alarm_control_panel.alarm_arm_home({
                              ~~~~~~~~~~~~~~~~~~~

src/index.ts:190:27 - error TS2339: Property 'alarm_control_panel' does not exist on type 'iCallService'.

190     return hass.hass.call.alarm_control_panel.alarm_arm_night({
                              ~~~~~~~~~~~~~~~~~~~

src/index.ts:199:7 - error TS2322: Type 'TRawEntityIds' is not assignable to type '"light.bedroom_ceiling_fan" | "light.bedroom_ceiling_fan"[]'.
  Type '"person.digital_alchemy"' is not assignable to type '"light.bedroom_ceiling_fan" | "light.bedroom_ceiling_fan"[]'.

199       entity_id: params.entity_id,
          ~~~~~~~~~

src/index.ts:204:5 - error TS2322: Type 'TRawEntityIds' is not assignable to type '"light.bedroom_ceiling_fan" | "light.bedroom_ceiling_fan"[]'.
  Type '"person.digital_alchemy"' is not assignable to type '"light.bedroom_ceiling_fan" | "light.bedroom_ceiling_fan"[]'.

204     entity_id: params.entity_id,
        ~~~~~~~~~

src/index.ts:209:25 - error TS2339: Property 'climate' does not exist on type 'iCallService'.

209   return hass.hass.call.climate.set_temperature({
                            ~~~~~~~

src/index.ts:217:27 - error TS2339: Property 'cover' does not exist on type 'iCallService'.

217     return hass.hass.call.cover.set_cover_position({
                              ~~~~~

src/index.ts:223:27 - error TS2339: Property 'cover' does not exist on type 'iCallService'.

223     return hass.hass.call.cover.open_cover({
                              ~~~~~

src/index.ts:228:27 - error TS2339: Property 'cover' does not exist on type 'iCallService'.

228     return hass.hass.call.cover.close_cover({
                              ~~~~~


Found 12 errors in the same file, starting at: src/index.ts:165
```

Are you in the middle of a development ? Should we wait for a newer version of the code ?

**Comment by mfmanca2000** [comment]
Which version of @digital-alchemy hass and core should we use ?
It looks all those errors are related to those libraries

**Comment by tevonsb** [comment]
I'll take a look now and double check, that should be included in the package.json though. 

I haven't tried this myself with yarn 4.6.0. Known to be working with yarn 1.22.x
